### ISSUE TITLE
chatGPT4 option not available in released version

### ISSUE THREAD

**Issue by sporring** [royerlab/napari-chatgpt#16]
In the recommended install version, the gpt-4 option is not available, only various versions of gpt3.5.

**Comment by royerloic** [comment]
This is weird; I get the list of models from the OpenAI API, 
so if it does not show up, it means you don't have access,
But I believe that the API for 4 is accessible to all by now.
Could you post a screenshot of the model list with the latest version?
Thanks!

**Comment by royerloic** [comment]
Ok, turns out that you have to have made at least one payment to OpenAI (at least 1$),
to be granted access to GPT4. See below:

<img width="673" alt="image" src="https://github.com/royerlab/napari-chatgpt/assets/1870994/16475613-0b51-46a1-a70e-b27e5ea3dedd">

as seen here:
https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4
